/* ============================================================
   renderer.js — All canvas drawing, plus Path2D caching
   ============================================================
   createRenderer(ctx) returns a render function that draws the
   whole scene from the app `state` object.

   View transform: the whole scene is drawn under state.view
   (zoom + pan). All line widths, radii and marker sizes are
   SCREEN-CONSTANT — they are divided by the zoom so the mesh
   stays crisp whether zoomed in or out. The background grid is
   generated per view (state.viewCells) so it always fills the
   visible area.

   Performance: static paths are cached and rebuilt only when
   their input data changes (identity checks). Pointer moves
   re-render every frame but reuse the cached paths.

   Depends on:  constants.js, geometry.js, mesh.js (boundaryEdges)
   Exposes:     window.MeshStudio.Renderer
   ============================================================ */

(function (global) {
  'use strict';

  const Constants = global.MeshStudio.Constants;
  const COLORS = Constants.COLORS;
  const V = global.MeshStudio.Geometry.V;
  const Mesh = global.MeshStudio.Mesh;

  function createRenderer(ctx) {

    /** Screen-space size (px) converted to world units under the view. */
    function screen(state, px) {
      return px / state.view.zoom;
    }

    /**
     * Whether the renderer must skip mesh/polygon/node drawing. Prefers the
     * per-frame predicate state.hideMeshFn (set by the elastic block, whose
     * deformed-mode switch must take effect immediately) and falls back to
     * the static state.hideMesh boolean.
     */
    function isMeshHidden(s) {
      if (typeof s.hideMeshFn === 'function') return s.hideMeshFn();
      return !!s.hideMesh;
    }

    /** Trace one polygon ring into an existing Path2D. */
    function addPath(path, poly) {
      path.moveTo(poly[0].x, poly[0].y);
      for (let i = 1; i < poly.length; i++) path.lineTo(poly[i].x, poly[i].y);
      path.closePath();
    }

    /* ---------- Cached Path2D objects ---------- */
    let cachedCells = null, gridPath = null;
    let cachedMesh  = null, interiorPath = null, boundaryPath = null;
    let cachedOutline = null, outlinePath = null; // plain-mode outer boundary
    let cachedNodes = null, cachedNodesZoom = 1, nodePaths = null;

    function drawGrid(state) {
      // Background lattice fills the current view (state.viewCells is
      // regenerated by the app whenever the view or grid changes).
      const cells = state.viewCells || state.cells;
      if (cells !== cachedCells) {
        cachedCells = cells;
        gridPath = new Path2D();
        for (const cell of cells) addPath(gridPath, cell);
      }
      ctx.strokeStyle = COLORS.gridLine;
      ctx.lineWidth = screen(state, 1);
      ctx.stroke(gridPath);
    }

    function drawMesh(state) {
      if (!state.mesh) return;
      if (isMeshHidden(state)) return; // a solver block draws the domain itself
      if (state.mesh !== cachedMesh) {
        cachedMesh = state.mesh;
        interiorPath = new Path2D();
        boundaryPath = new Path2D();
        for (const el of state.mesh.elements) {
          const poly = el.nodeIds.map(id => state.mesh.nodes[id]);
          addPath(el.interior ? interiorPath : boundaryPath, poly);
        }
      }
      const plain = state.meshPlain === true;
      // Plain mode (solve phase): no element fills and no interior cell
      // edges — only the OUTER domain boundary outline is drawn, so the
      // heatmap underneath is neither tinted nor cluttered.
      if (plain) {
        if (state.mesh !== cachedOutline) {
          cachedOutline = state.mesh;
          outlinePath = new Path2D();
          for (const [a, b] of Mesh.boundaryEdges(state.mesh)) {
            outlinePath.moveTo(state.mesh.nodes[a].x, state.mesh.nodes[a].y);
            outlinePath.lineTo(state.mesh.nodes[b].x, state.mesh.nodes[b].y);
          }
        }
        ctx.strokeStyle = COLORS.boundaryEdge;
        ctx.lineWidth = screen(state, 2.5);
        ctx.stroke(outlinePath);
        return;
      }
      // Normal (pre-processing) mode: colored fills + interior edges +
      // boundary edges.
      ctx.fillStyle = COLORS.interiorFill;
      ctx.fill(interiorPath);
      ctx.strokeStyle = COLORS.interiorEdge;
      ctx.lineWidth = screen(state, 1.5);
      ctx.stroke(interiorPath);
      ctx.fillStyle = COLORS.boundaryFill;
      ctx.fill(boundaryPath);
      ctx.strokeStyle = COLORS.boundaryEdge;
      ctx.lineWidth = screen(state, 2.5);
      ctx.stroke(boundaryPath);
    }

    function drawPolygon(state) {
      if (isMeshHidden(state)) return; // solver block renders the domain itself
      const poly = state.polygon;
      if (!poly || poly.length < 3) return;
      const path = new Path2D();
      addPath(path, poly);
      ctx.fillStyle = COLORS.polygonFill;
      ctx.fill(path);
      ctx.strokeStyle = COLORS.polygon;
      ctx.lineWidth = screen(state, 1.5);
      ctx.stroke(path);
    }

    function drawNodes(state) {
      if (!state.mesh) return;
      if (isMeshHidden(state)) return; // solver block draws its own markers
      const styles = [
        { type: 'grid',         color: COLORS.nodeGrid,      r: 2.5 },
        { type: 'sampling',     color: COLORS.nodeSampling,  r: 3.5 },
        { type: 'intersection', color: COLORS.nodeIntersect, r: 3.5 },
      ];
      // Node radii are screen-constant, so the cached paths depend on BOTH
      // the mesh and the current zoom.
      if (state.mesh !== cachedNodes || state.view.zoom !== cachedNodesZoom) {
        cachedNodes = state.mesh;
        cachedNodesZoom = state.view.zoom;
        // One Path2D + single fill per type keeps dense node sets fast.
        nodePaths = styles.map(({ type, color, r }) => {
          const rr = screen(state, r);
          const path = new Path2D();
          for (const n of state.mesh.nodes) {
            if ((n.type || 'grid') !== type) continue;
            path.moveTo(n.x + rr, n.y);
            path.arc(n.x, n.y, rr, 0, Math.PI * 2);
          }
          return { color, path };
        });
      }
      for (const { color, path } of nodePaths) {
        ctx.fillStyle = color;
        ctx.fill(path);
      }
    }

    function drawPreview(state) {
      if (!state.drawing.length) return;
      const pts = state.drawing;
      const freehand = state.drawMode === 'freehand';

      // Path stroke: solid for freehand, dashed for click-to-point.
      ctx.beginPath();
      ctx.moveTo(pts[0].x, pts[0].y);
      for (let i = 1; i < pts.length; i++) ctx.lineTo(pts[i].x, pts[i].y);
      ctx.strokeStyle = COLORS.polygonStroke;
      ctx.lineWidth = screen(state, freehand ? 2 : 1.5);
      if (!freehand) ctx.setLineDash([6, 5]);
      ctx.stroke();
      ctx.setLineDash([]);

      if (freehand) {
        // Hint the implicit closing edge back to the stroke start.
        if (pts.length > 2 && state.cursor) {
          ctx.beginPath();
          ctx.moveTo(pts[pts.length - 1].x, pts[pts.length - 1].y);
          ctx.lineTo(pts[0].x, pts[0].y);
          ctx.strokeStyle = COLORS.polygonGuide;
          ctx.setLineDash([4, 4]);
          ctx.stroke();
          ctx.setLineDash([]);
        }
        return;
      }

      // Click-to-point: discrete vertices + guide to cursor + close highlight.
      for (const p of pts) {
        ctx.beginPath();
        ctx.arc(p.x, p.y, screen(state, 4), 0, Math.PI * 2);
        ctx.fillStyle = COLORS.vertexFill;
        ctx.fill();
        ctx.strokeStyle = COLORS.polygon;
        ctx.lineWidth = screen(state, 1.5);
        ctx.stroke();
      }

      if (state.cursor) {
        ctx.beginPath();
        ctx.moveTo(pts[pts.length - 1].x, pts[pts.length - 1].y);
        ctx.lineTo(state.cursor.x, state.cursor.y);
        ctx.strokeStyle = COLORS.polygonGuide;
        ctx.setLineDash([4, 4]);
        ctx.stroke();
        ctx.setLineDash([]);

        // 12 px is a screen-space tolerance; convert to world units.
        if (pts.length >= 3 && V.dist(state.cursor, pts[0]) < 12 / state.view.zoom) {
          ctx.beginPath();
          ctx.arc(pts[0].x, pts[0].y, screen(state, 8), 0, Math.PI * 2);
          ctx.strokeStyle = COLORS.polygonStroke;
          ctx.lineWidth = screen(state, 1.5);
          ctx.stroke();
        }
      }
    }

    /* ============================================================
       Boundary conditions (loads / supports) markers + selection
       ============================================================ */

    /**
     * Arrow from (x,y) along direction (dx,dy).
     * L and width are SCREEN px (converted to world by k = 1/zoom).
     */
    function drawArrow(x, y, dx, dy, L, color, width, k) {
      const len = Math.hypot(dx, dy);
      if (len < 1e-9) return; // zero vector: no arrow
      const ux = dx / len, uy = dy / len;
      const x2 = x + ux * L * k, y2 = y + uy * L * k;
      ctx.strokeStyle = color;
      ctx.lineWidth = width * k;
      ctx.beginPath();
      ctx.moveTo(x, y);
      ctx.lineTo(x2, y2);
      ctx.stroke();
      const head = 5.5 * k, ang = 0.42;
      ctx.beginPath();
      ctx.moveTo(x2, y2);
      ctx.lineTo(x2 - Math.cos(Math.atan2(uy, ux) - ang) * head, y2 - Math.sin(Math.atan2(uy, ux) - ang) * head);
      ctx.moveTo(x2, y2);
      ctx.lineTo(x2 - Math.cos(Math.atan2(uy, ux) + ang) * head, y2 - Math.sin(Math.atan2(uy, ux) + ang) * head);
      ctx.stroke();
    }

    /** Support marker: fixed = filled triangle, hinge = outlined triangle. */
    function drawSupport(x, y, type, color, k) {
      const filled = type === 'fixed';
      ctx.beginPath();
      ctx.moveTo(x - 6 * k, y + 9 * k);
      ctx.lineTo(x + 6 * k, y + 9 * k);
      ctx.lineTo(x, y);
      ctx.closePath();
      ctx.fillStyle = filled ? color : 'rgba(255,255,255,0.7)';
      ctx.strokeStyle = color;
      ctx.lineWidth = 1.5 * k;
      if (filled) ctx.fill();
      ctx.stroke();
      if (filled) { // ground hatch
        ctx.beginPath();
        ctx.moveTo(x - 10 * k, y + 12 * k); ctx.lineTo(x + 10 * k, y + 12 * k);
        ctx.moveTo(x - 7 * k, y + 15 * k); ctx.lineTo(x + 7 * k, y + 15 * k);
        ctx.moveTo(x - 4 * k, y + 18 * k); ctx.lineTo(x + 4 * k, y + 18 * k);
        ctx.strokeStyle = color;
        ctx.lineWidth = 1 * k;
        ctx.stroke();
      }
    }

    function drawConditions(state) {
      const mesh = state.mesh;
      if (!mesh) return;
      // Pre-processor mechanical BC markers (loads / supports) only belong
      // to problems that CONSUME them (2D Elasticity, flag usesPreprocBCs).
      // During the solve phase of problems with different BC physics (e.g.
      // Poisson's scalar Dirichlet/Neumann) they are hidden — evaluated
      // per frame against the ACTIVE block's metadata.
      if (state.phase === 'solve') {
        const UI = global.MeshStudio && global.MeshStudio.SolverUI;
        const blk = UI && UI.currentProblem ? UI.blocks[UI.currentProblem()] : null;
        if (!blk || !blk.usesPreprocBCs) return;
      }
      const colors = Constants.COND_COLORS;
      const k = 1 / state.view.zoom; // screen px -> world units

      // --- live selection preview ---
      const sel = state.bcSel;
      if (sel) {
        if (sel.nodes && sel.nodes.size) {
          ctx.fillStyle = 'rgba(0,113,227,0.35)';
          for (const id of sel.nodes) {
            const n = mesh.nodes[id];
            ctx.beginPath();
            ctx.arc(n.x, n.y, 7 * k, 0, Math.PI * 2);
            ctx.fill();
          }
        }
        if (sel.edges && sel.edges.size) {
          ctx.strokeStyle = 'rgba(0,113,227,0.6)';
          ctx.lineWidth = 5 * k;
          ctx.beginPath();
          for (const [a, b] of sel.edges.values()) {
            const na = mesh.nodes[a], nb = mesh.nodes[b];
            ctx.moveTo(na.x, na.y);
            ctx.lineTo(nb.x, nb.y);
          }
          ctx.stroke();
        }
        if (sel.box) {
          const b = sel.box;
          ctx.fillStyle = 'rgba(0,113,227,0.08)';
          ctx.strokeStyle = 'rgba(0,113,227,0.5)';
          ctx.lineWidth = 1 * k;
          ctx.setLineDash([4 * k, 3 * k]);
          ctx.fillRect(b.minX, b.minY, b.maxX - b.minX, b.maxY - b.minY);
          ctx.strokeRect(b.minX, b.minY, b.maxX - b.minX, b.maxY - b.minY);
          ctx.setLineDash([]);
        }
      }

      // --- confirmed groups ---
      const color = i => colors[i % colors.length];

      state.pointLoads.forEach((g, gi) => {
        const col = color(gi);
        for (const id of g.nodeIds) {
          const n = mesh.nodes[id];
          ctx.beginPath();
          ctx.arc(n.x, n.y, 6 * k, 0, Math.PI * 2);
          ctx.fillStyle = 'rgba(255,255,255,0.85)';
          ctx.fill();
          ctx.strokeStyle = col;
          ctx.lineWidth = 2 * k;
          ctx.stroke();
          // Load vectors use the FEM convention (+Y = up); the canvas is
          // Y-down, so the arrow direction flips the Y component.
          drawArrow(n.x, n.y, g.fx, -g.fy, 18, col, 2, k);
        }
      });

      state.distLoads.forEach((g, gi) => {
        const col = color(gi);
        for (const [a, b] of g.edges) {
          const na = mesh.nodes[a], nb = mesh.nodes[b];
          const mx = (na.x + nb.x) / 2, my = (na.y + nb.y) / 2;
          ctx.beginPath();
          ctx.moveTo(na.x, na.y);
          ctx.lineTo(nb.x, nb.y);
          ctx.strokeStyle = col;
          ctx.lineWidth = 3 * k;
          ctx.stroke();
          drawArrow(mx, my, g.fx, -g.fy, 14, col, 2, k);
        }
      });

      state.supports.forEach((g, gi) => {
        const col = color(gi);
        for (const id of g.nodeIds) drawSupport(mesh.nodes[id].x, mesh.nodes[id].y, g.type, col, k);
      });
    }

    /** Draw the complete scene from the current app state. */
    function render(state) {
      // Reset to the device transform so the clear/fill cover the whole
      // canvas, then apply the view transform (zoom + optional pan).
      ctx.setTransform(state.dpr, 0, 0, state.dpr, 0, 0);
      ctx.clearRect(0, 0, state.w, state.h);
      ctx.fillStyle = COLORS.background;
      ctx.fillRect(0, 0, state.w, state.h);
      const v = state.view;
      ctx.setTransform(state.dpr * v.zoom, 0, 0, state.dpr * v.zoom, state.dpr * v.ox, state.dpr * v.oy);

      drawGrid(state);
      // Underlay hooks (heatmap etc.) are drawn BELOW the mesh so the
      // original polygonal cell edges stay visible on top of the fill.
      if (state.underlayHooks) {
        for (const fn of state.underlayHooks) fn(ctx);
      }
      drawMesh(state);
      // In the solve phase (meshPlain) the polygon overlay and node dots
      // stay visible; only the mesh itself is drawn plain.
      drawPolygon(state);
      drawNodes(state);
      drawConditions(state);
      drawPreview(state);
      // Phase plugins (solver shell etc.) can inject extra drawing (BC
      // markers, heatmap) — runs under the same view transform.
      if (state.renderHooks) {
        for (const fn of state.renderHooks) fn(ctx);
      }
    }

    return { render };
  }

  /* ---------- Public API ---------- */

  global.MeshStudio = global.MeshStudio || {};
  global.MeshStudio.Renderer = { createRenderer };
})(window);
